### ISSUE TITLE
Add testing to SOP and validate with a running example

### ISSUE THREAD

**Issue by costateixeira** [WorldHealthOrganization/smart-ig-starter-kit#70]
As an L3 author, I want the L3 SOPs to include testing and testability as part of the authoring process, so that I can validate that my authored content is not only technically sound but will deliver the expectations of L2.

Acceptance criteria:
* A standard procedure for using test criteria and test artifacts (test cases, test scenarios, test assertions... ) shall be included as part of the L3 authoring
* Tooling for executing the tests shall be identified
* The test tooling should be setup in a pipeline as part of the build process - so that when an author makes a change, the testing accompanies that change, and the author can see whether that change is successfully tested.
* An example of testability shall be added to a SMART Guideline
* All the technical artifacts that are produced in L3 should be subject of tests
* Functional tests should use the example resources that are in the L3 authoring; other tests may use resources that are outside of the Implementation Guide. That approach shall also be documented and tooling prepared.
* The way to produce or define large test data shall be documented and should be included in the tools.

```[tasklist]
### Tasks
- [ ] Document usage of test artifacts
- [ ] Add testing to sample IG
- [ ] setup tooling
- [ ] Demonstrate in Virtual Encounter (Q1 2024)
```
